# -*- coding: utf-8 -*-
"""Scientific calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhpV8oszv2z2mPxuz39WliVA5WK6QFI5
"""

import math

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Error! Division by zero."

def power(x, y):
    return x ** y

def square_root(x):
    if x >= 0:
        return math.sqrt(x)
    else:
        return "Error! Square root of negative number."

def sine(x):
    return math.sin(math.radians(x))

def cosine(x):
    return math.cos(math.radians(x))

def tangent(x):
    return math.tan(math.radians(x))

def calculator():
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Power")
    print("6. Square Root")
    print("7. Sine")
    print("8. Cosine")
    print("9. Tangent")

    while True:
        choice = input("Enter choice (1-9): ")

        if choice in ['1', '2', '3', '4', '5', '6', '7', '8', '9']:
            if choice in ['1', '2', '3', '4', '5']:
                num1 = float(input("Enter first number: "))
                num2 = float(input("Enter second number: "))

                if choice == '1':
                    print(f"{num1} + {num2} = {add(num1, num2)}")
                elif choice == '2':
                    print(f"{num1} - {num2} = {subtract(num1, num2)}")
                elif choice == '3':
                    print(f"{num1} * {num2} = {multiply(num1, num2)}")
                elif choice == '4':
                    print(f"{num1} / {num2} = {divide(num1, num2)}")
                elif choice == '5':
                    print(f"{num1} ^ {num2} = {power(num1, num2)}")

            elif choice == '6':
                num = float(input("Enter number: "))
                print(f"Square root of {num} = {square_root(num)}")

            elif choice in ['7', '8', '9']:
                angle = float(input("Enter angle in degrees: "))
                if choice == '7':
                    print(f"Sine of {angle} degrees = {sine(angle)}")
                elif choice == '8':
                    print(f"Cosine of {angle} degrees = {cosine(angle)}")
                elif choice == '9':
                    print(f"Tangent of {angle} degrees = {tangent(angle)}")
        else:
            print("Invalid input! Please enter a number between 1 to 9.")

        # Check if the user wants to perform another calculation
        next_calculation = input("Do you want to perform another calculation? (yes/no): ")
        if next_calculation.lower() != 'yes':
            break

if __name__ == "__main__":
    calculator()